const actionTypes = {
  SIGNUP: "SIGNUP",
  LOGIN: "LOGIN",
  SIGNUPFAIL: "SIGNUPFAIL",
  SIGNUPSUCCESS: "SIGNUPSUCCESS",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED",
};

export default actionTypes;
