const actionTypes = {
  SIGNUP: "SIGNUP",
  LOGIN: "LOGIN",
  SIGNUPFAIL: "SIGNUPFAIL",
  SIGNUPSUCCESS: "SIGNUPSUCCESS",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED",
  FOLLOW_USER: "FOLLOW_USER",
  UNFOLLOW_USER: "UNFOLLOW_USER",
  GET_FOLLOWING: "GET_FOLLOWING",
  GET_FOLLOWERS: "GET_FOLLOWERS"
};

export default actionTypes;
