const commentsActionTypes = {
  FETCH_COMMENTS: "FETCH_COMMENTS",
  FETCH_COMMENTS_ERROR: "FETCH_COMMENTS_ERROR",
  ADD_COMMENT: "ADD_COMMENT",
  LIKE_COMMENT: "LIKE_COMMENT",
  LIKE_COMMENT_ERROR: "LIKE_COMMENT_ERROR",
  ADD_COMMENT_ERROR: "ADD_COMMENT_ERROR",
  DELETE_COMMENT: "DELETE COMMENT",
  DELETE_COMMENT_ERROR: "DELETE_COMMENT_ERROR",
  EDIT_COMMENT_SUCCESS: "EDIT_COMMENT_SUCCESS",
  EDIT_COMMENT_ERROR: "EDIT_COMMENT_ERROR",

};

export default commentsActionTypes;
