const BookmarkActionTypes = {
    ADD_BOOKMARK: 'ADD_BOOKMARK',
    ADD_BOOKMARK_ERROR: 'ADD_BOOKMARK_ERROR',
    FETCH_BOOKMARKS: 'FETCH_BOOKMARKS',
    FETCH_BOOKMARKS_ERROR: 'FETCH_BOOKMARKS_ERROR',
    DELETE_BOOKMARK: 'DELETE_BOOKMARK',
    DELETE_BOOKMARK_ERROR: 'DELETE_BOOKMARK_ERROR'
};

export default BookmarkActionTypes;
